// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: metering.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeteringEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	BytesIn       int64                  `protobuf:"varint,4,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut      int64                  `protobuf:"varint,5,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	StatusCode    int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Success       bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeteringEvent) Reset() {
	*x = MeteringEvent{}
	mi := &file_metering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteringEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteringEvent) ProtoMessage() {}

func (x *MeteringEvent) ProtoReflect() protoreflect.Message {
	mi := &file_metering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteringEvent.ProtoReflect.Descriptor instead.
func (*MeteringEvent) Descriptor() ([]byte, []int) {
	return file_metering_proto_rawDescGZIP(), []int{0}
}

func (x *MeteringEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MeteringEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MeteringEvent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MeteringEvent) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *MeteringEvent) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *MeteringEvent) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *MeteringEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *MeteringEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MeteringEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MeteringReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Events          []*MeteringEvent       `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	ReportTimestamp int64                  `protobuf:"varint,3,opt,name=report_timestamp,json=reportTimestamp,proto3" json:"report_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeteringReport) Reset() {
	*x = MeteringReport{}
	mi := &file_metering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteringReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteringReport) ProtoMessage() {}

func (x *MeteringReport) ProtoReflect() protoreflect.Message {
	mi := &file_metering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteringReport.ProtoReflect.Descriptor instead.
func (*MeteringReport) Descriptor() ([]byte, []int) {
	return file_metering_proto_rawDescGZIP(), []int{1}
}

func (x *MeteringReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MeteringReport) GetEvents() []*MeteringEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *MeteringReport) GetReportTimestamp() int64 {
	if x != nil {
		return x.ReportTimestamp
	}
	return 0
}

type MeteringSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalBytesIn       int64                  `protobuf:"varint,2,opt,name=total_bytes_in,json=totalBytesIn,proto3" json:"total_bytes_in,omitempty"`
	TotalBytesOut      int64                  `protobuf:"varint,3,opt,name=total_bytes_out,json=totalBytesOut,proto3" json:"total_bytes_out,omitempty"`
	TotalRequests      int32                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests int32                  `protobuf:"varint,5,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	AvgLatencyMs       int32                  `protobuf:"varint,6,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	PeriodStart        int64                  `protobuf:"varint,7,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd          int64                  `protobuf:"varint,8,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MeteringSummary) Reset() {
	*x = MeteringSummary{}
	mi := &file_metering_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteringSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteringSummary) ProtoMessage() {}

func (x *MeteringSummary) ProtoReflect() protoreflect.Message {
	mi := &file_metering_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteringSummary.ProtoReflect.Descriptor instead.
func (*MeteringSummary) Descriptor() ([]byte, []int) {
	return file_metering_proto_rawDescGZIP(), []int{2}
}

func (x *MeteringSummary) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MeteringSummary) GetTotalBytesIn() int64 {
	if x != nil {
		return x.TotalBytesIn
	}
	return 0
}

func (x *MeteringSummary) GetTotalBytesOut() int64 {
	if x != nil {
		return x.TotalBytesOut
	}
	return 0
}

func (x *MeteringSummary) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MeteringSummary) GetSuccessfulRequests() int32 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *MeteringSummary) GetAvgLatencyMs() int32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *MeteringSummary) GetPeriodStart() int64 {
	if x != nil {
		return x.PeriodStart
	}
	return 0
}

func (x *MeteringSummary) GetPeriodEnd() int64 {
	if x != nil {
		return x.PeriodEnd
	}
	return 0
}

var File_metering_proto protoreflect.FileDescriptor

const file_metering_proto_rawDesc = "" +
	"\n" +
	"\x0emetering.proto\x12\x15proxycoin.protocol.v1\"\x98\x02\n" +
	"\rMeteringEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\bbytes_in\x18\x04 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x05 \x01(\x03R\bbytesOut\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x05R\tlatencyMs\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\x92\x01\n" +
	"\x0eMeteringReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12<\n" +
	"\x06events\x18\x02 \x03(\v2$.proxycoin.protocol.v1.MeteringEventR\x06events\x12)\n" +
	"\x10report_timestamp\x18\x03 \x01(\x03R\x0freportTimestamp\"\xb8\x02\n" +
	"\x0fMeteringSummary\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12$\n" +
	"\x0etotal_bytes_in\x18\x02 \x01(\x03R\ftotalBytesIn\x12&\n" +
	"\x0ftotal_bytes_out\x18\x03 \x01(\x03R\rtotalBytesOut\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x05R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x05 \x01(\x05R\x12successfulRequests\x12$\n" +
	"\x0eavg_latency_ms\x18\x06 \x01(\x05R\favgLatencyMs\x12!\n" +
	"\fperiod_start\x18\a \x01(\x03R\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\b \x01(\x03R\tperiodEndBf\n" +
	"\x1acom.proxycoin.app.protocolB\rMeteringProtoZ9github.com/gofullthrottle/proxy-coin/backend/pkg/protocolb\x06proto3"

var (
	file_metering_proto_rawDescOnce sync.Once
	file_metering_proto_rawDescData []byte
)

func file_metering_proto_rawDescGZIP() []byte {
	file_metering_proto_rawDescOnce.Do(func() {
		file_metering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metering_proto_rawDesc), len(file_metering_proto_rawDesc)))
	})
	return file_metering_proto_rawDescData
}

var file_metering_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_metering_proto_goTypes = []any{
	(*MeteringEvent)(nil),   // 0: proxycoin.protocol.v1.MeteringEvent
	(*MeteringReport)(nil),  // 1: proxycoin.protocol.v1.MeteringReport
	(*MeteringSummary)(nil), // 2: proxycoin.protocol.v1.MeteringSummary
}
var file_metering_proto_depIdxs = []int32{
	0, // 0: proxycoin.protocol.v1.MeteringReport.events:type_name -> proxycoin.protocol.v1.MeteringEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metering_proto_init() }
func file_metering_proto_init() {
	if File_metering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metering_proto_rawDesc), len(file_metering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metering_proto_goTypes,
		DependencyIndexes: file_metering_proto_depIdxs,
		MessageInfos:      file_metering_proto_msgTypes,
	}.Build()
	File_metering_proto = out.File
	file_metering_proto_goTypes = nil
	file_metering_proto_depIdxs = nil
}
