// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: node.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node registration
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	DeviceModel   string                 `protobuf:"bytes,5,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	NetworkType   string                 `protobuf:"bytes,6,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"` // wifi, cellular
	MaxConcurrent int32                  `protobuf:"varint,7,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *RegisterRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *RegisterRequest) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *RegisterRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Config        *NodeConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *NodeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type NodeConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PrxyPerMb           float64                `protobuf:"fixed64,1,opt,name=prxy_per_mb,json=prxyPerMb,proto3" json:"prxy_per_mb,omitempty"`
	HeartbeatIntervalMs int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	MaxConcurrent       int32                  `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	BlocklistHash       []byte                 `protobuf:"bytes,4,opt,name=blocklist_hash,json=blocklistHash,proto3" json:"blocklist_hash,omitempty"`
	BlocklistVersion    int64                  `protobuf:"varint,5,opt,name=blocklist_version,json=blocklistVersion,proto3" json:"blocklist_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeConfig) GetPrxyPerMb() float64 {
	if x != nil {
		return x.PrxyPerMb
	}
	return 0
}

func (x *NodeConfig) GetHeartbeatIntervalMs() int32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *NodeConfig) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *NodeConfig) GetBlocklistHash() []byte {
	if x != nil {
		return x.BlocklistHash
	}
	return nil
}

func (x *NodeConfig) GetBlocklistVersion() int64 {
	if x != nil {
		return x.BlocklistVersion
	}
	return 0
}

type Heartbeat struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeId                string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UptimeSeconds         int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveRequests        int32                  `protobuf:"varint,3,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	BatteryLevel          float32                `protobuf:"fixed32,4,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	IsCharging            bool                   `protobuf:"varint,5,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	NetworkType           string                 `protobuf:"bytes,6,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	CpuTemperature        float32                `protobuf:"fixed32,7,opt,name=cpu_temperature,json=cpuTemperature,proto3" json:"cpu_temperature,omitempty"`
	BytesProxiedSinceLast int64                  `protobuf:"varint,8,opt,name=bytes_proxied_since_last,json=bytesProxiedSinceLast,proto3" json:"bytes_proxied_since_last,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *Heartbeat) GetBatteryLevel() float32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *Heartbeat) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *Heartbeat) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *Heartbeat) GetCpuTemperature() float32 {
	if x != nil {
		return x.CpuTemperature
	}
	return 0
}

func (x *Heartbeat) GetBytesProxiedSinceLast() int64 {
	if x != nil {
		return x.BytesProxiedSinceLast
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *NodeConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigUpdate) GetConfig() *NodeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type EarningsUpdate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TodayEarnings       float64                `protobuf:"fixed64,1,opt,name=today_earnings,json=todayEarnings,proto3" json:"today_earnings,omitempty"`
	AllTimeEarnings     float64                `protobuf:"fixed64,2,opt,name=all_time_earnings,json=allTimeEarnings,proto3" json:"all_time_earnings,omitempty"`
	PendingClaim        float64                `protobuf:"fixed64,3,opt,name=pending_claim,json=pendingClaim,proto3" json:"pending_claim,omitempty"`
	TrustScore          float64                `protobuf:"fixed64,4,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	RequestsServedToday int64                  `protobuf:"varint,5,opt,name=requests_served_today,json=requestsServedToday,proto3" json:"requests_served_today,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EarningsUpdate) Reset() {
	*x = EarningsUpdate{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarningsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarningsUpdate) ProtoMessage() {}

func (x *EarningsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarningsUpdate.ProtoReflect.Descriptor instead.
func (*EarningsUpdate) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *EarningsUpdate) GetTodayEarnings() float64 {
	if x != nil {
		return x.TodayEarnings
	}
	return 0
}

func (x *EarningsUpdate) GetAllTimeEarnings() float64 {
	if x != nil {
		return x.AllTimeEarnings
	}
	return 0
}

func (x *EarningsUpdate) GetPendingClaim() float64 {
	if x != nil {
		return x.PendingClaim
	}
	return 0
}

func (x *EarningsUpdate) GetTrustScore() float64 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *EarningsUpdate) GetRequestsServedToday() int64 {
	if x != nil {
		return x.RequestsServedToday
	}
	return 0
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x15proxycoin.protocol.v1\"\x82\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12!\n" +
	"\fdevice_model\x18\x05 \x01(\tR\vdeviceModel\x12!\n" +
	"\fnetwork_type\x18\x06 \x01(\tR\vnetworkType\x12%\n" +
	"\x0emax_concurrent\x18\a \x01(\x05R\rmaxConcurrent\"f\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\x06config\x18\x02 \x01(\v2!.proxycoin.protocol.v1.NodeConfigR\x06config\"\xdb\x01\n" +
	"\n" +
	"NodeConfig\x12\x1e\n" +
	"\vprxy_per_mb\x18\x01 \x01(\x01R\tprxyPerMb\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x05R\x13heartbeatIntervalMs\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x05R\rmaxConcurrent\x12%\n" +
	"\x0eblocklist_hash\x18\x04 \x01(\fR\rblocklistHash\x12+\n" +
	"\x11blocklist_version\x18\x05 \x01(\x03R\x10blocklistVersion\"\xbf\x02\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0factive_requests\x18\x03 \x01(\x05R\x0eactiveRequests\x12#\n" +
	"\rbattery_level\x18\x04 \x01(\x02R\fbatteryLevel\x12\x1f\n" +
	"\vis_charging\x18\x05 \x01(\bR\n" +
	"isCharging\x12!\n" +
	"\fnetwork_type\x18\x06 \x01(\tR\vnetworkType\x12'\n" +
	"\x0fcpu_temperature\x18\a \x01(\x02R\x0ecpuTemperature\x127\n" +
	"\x18bytes_proxied_since_last\x18\b \x01(\x03R\x15bytesProxiedSinceLast\"/\n" +
	"\fHeartbeatAck\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"I\n" +
	"\fConfigUpdate\x129\n" +
	"\x06config\x18\x01 \x01(\v2!.proxycoin.protocol.v1.NodeConfigR\x06config\"\xdd\x01\n" +
	"\x0eEarningsUpdate\x12%\n" +
	"\x0etoday_earnings\x18\x01 \x01(\x01R\rtodayEarnings\x12*\n" +
	"\x11all_time_earnings\x18\x02 \x01(\x01R\x0fallTimeEarnings\x12#\n" +
	"\rpending_claim\x18\x03 \x01(\x01R\fpendingClaim\x12\x1f\n" +
	"\vtrust_score\x18\x04 \x01(\x01R\n" +
	"trustScore\x122\n" +
	"\x15requests_served_today\x18\x05 \x01(\x03R\x13requestsServedTodayBb\n" +
	"\x1acom.proxycoin.app.protocolB\tNodeProtoZ9github.com/gofullthrottle/proxy-coin/backend/pkg/protocolb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_node_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: proxycoin.protocol.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: proxycoin.protocol.v1.RegisterResponse
	(*NodeConfig)(nil),       // 2: proxycoin.protocol.v1.NodeConfig
	(*Heartbeat)(nil),        // 3: proxycoin.protocol.v1.Heartbeat
	(*HeartbeatAck)(nil),     // 4: proxycoin.protocol.v1.HeartbeatAck
	(*ConfigUpdate)(nil),     // 5: proxycoin.protocol.v1.ConfigUpdate
	(*EarningsUpdate)(nil),   // 6: proxycoin.protocol.v1.EarningsUpdate
}
var file_node_proto_depIdxs = []int32{
	2, // 0: proxycoin.protocol.v1.RegisterResponse.config:type_name -> proxycoin.protocol.v1.NodeConfig
	2, // 1: proxycoin.protocol.v1.ConfigUpdate.config:type_name -> proxycoin.protocol.v1.NodeConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
