// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proxy.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyMethod int32

const (
	ProxyMethod_PROXY_METHOD_UNSPECIFIED ProxyMethod = 0
	ProxyMethod_GET                      ProxyMethod = 1
	ProxyMethod_POST                     ProxyMethod = 2
	ProxyMethod_PUT                      ProxyMethod = 3
	ProxyMethod_DELETE                   ProxyMethod = 4
	ProxyMethod_PATCH                    ProxyMethod = 5
	ProxyMethod_HEAD                     ProxyMethod = 6
	ProxyMethod_OPTIONS                  ProxyMethod = 7
	ProxyMethod_CONNECT                  ProxyMethod = 8
)

// Enum value maps for ProxyMethod.
var (
	ProxyMethod_name = map[int32]string{
		0: "PROXY_METHOD_UNSPECIFIED",
		1: "GET",
		2: "POST",
		3: "PUT",
		4: "DELETE",
		5: "PATCH",
		6: "HEAD",
		7: "OPTIONS",
		8: "CONNECT",
	}
	ProxyMethod_value = map[string]int32{
		"PROXY_METHOD_UNSPECIFIED": 0,
		"GET":                      1,
		"POST":                     2,
		"PUT":                      3,
		"DELETE":                   4,
		"PATCH":                    5,
		"HEAD":                     6,
		"OPTIONS":                  7,
		"CONNECT":                  8,
	}
)

func (x ProxyMethod) Enum() *ProxyMethod {
	p := new(ProxyMethod)
	*p = x
	return p
}

func (x ProxyMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[0].Descriptor()
}

func (ProxyMethod) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[0]
}

func (x ProxyMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyMethod.Descriptor instead.
func (ProxyMethod) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        ProxyMethod            `protobuf:"varint,2,opt,name=method,proto3,enum=proxycoin.protocol.v1.ProxyMethod" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers       []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProxyRequest) GetMethod() ProxyMethod {
	if x != nil {
		return x.Method
	}
	return ProxyMethod_PROXY_METHOD_UNSPECIFIED
}

func (x *ProxyRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProxyRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProxyRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ProxyResponseStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	ContentLength int64                  `protobuf:"varint,4,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponseStart) Reset() {
	*x = ProxyResponseStart{}
	mi := &file_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponseStart) ProtoMessage() {}

func (x *ProxyResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponseStart.ProtoReflect.Descriptor instead.
func (*ProxyResponseStart) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyResponseStart) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProxyResponseStart) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProxyResponseStart) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyResponseStart) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type ProxyResponseChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponseChunk) Reset() {
	*x = ProxyResponseChunk{}
	mi := &file_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponseChunk) ProtoMessage() {}

func (x *ProxyResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponseChunk.ProtoReflect.Descriptor instead.
func (*ProxyResponseChunk) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyResponseChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProxyResponseChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ProxyResponseChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProxyResponseEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponseEnd) Reset() {
	*x = ProxyResponseEnd{}
	mi := &file_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponseEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponseEnd) ProtoMessage() {}

func (x *ProxyResponseEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponseEnd.ProtoReflect.Descriptor instead.
func (*ProxyResponseEnd) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyResponseEnd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProxyResponseEnd) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ProxyResponseEnd) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ProxyResponseEnd) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProxyResponseEnd) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Wrapper message for WebSocket framing
type WebSocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebSocketMessage_RegisterRequest
	//	*WebSocketMessage_RegisterResponse
	//	*WebSocketMessage_Heartbeat
	//	*WebSocketMessage_HeartbeatAck
	//	*WebSocketMessage_ConfigUpdate
	//	*WebSocketMessage_EarningsUpdate
	//	*WebSocketMessage_ProxyRequest
	//	*WebSocketMessage_ProxyResponseStart
	//	*WebSocketMessage_ProxyResponseChunk
	//	*WebSocketMessage_ProxyResponseEnd
	Payload       isWebSocketMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *WebSocketMessage) GetPayload() isWebSocketMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebSocketMessage) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *WebSocketMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *WebSocketMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WebSocketMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *WebSocketMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *WebSocketMessage) GetEarningsUpdate() *EarningsUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_EarningsUpdate); ok {
			return x.EarningsUpdate
		}
	}
	return nil
}

func (x *WebSocketMessage) GetProxyRequest() *ProxyRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_ProxyRequest); ok {
			return x.ProxyRequest
		}
	}
	return nil
}

func (x *WebSocketMessage) GetProxyResponseStart() *ProxyResponseStart {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_ProxyResponseStart); ok {
			return x.ProxyResponseStart
		}
	}
	return nil
}

func (x *WebSocketMessage) GetProxyResponseChunk() *ProxyResponseChunk {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_ProxyResponseChunk); ok {
			return x.ProxyResponseChunk
		}
	}
	return nil
}

func (x *WebSocketMessage) GetProxyResponseEnd() *ProxyResponseEnd {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_ProxyResponseEnd); ok {
			return x.ProxyResponseEnd
		}
	}
	return nil
}

type isWebSocketMessage_Payload interface {
	isWebSocketMessage_Payload()
}

type WebSocketMessage_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,1,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type WebSocketMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type WebSocketMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type WebSocketMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,4,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type WebSocketMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,5,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type WebSocketMessage_EarningsUpdate struct {
	EarningsUpdate *EarningsUpdate `protobuf:"bytes,6,opt,name=earnings_update,json=earningsUpdate,proto3,oneof"`
}

type WebSocketMessage_ProxyRequest struct {
	ProxyRequest *ProxyRequest `protobuf:"bytes,7,opt,name=proxy_request,json=proxyRequest,proto3,oneof"`
}

type WebSocketMessage_ProxyResponseStart struct {
	ProxyResponseStart *ProxyResponseStart `protobuf:"bytes,8,opt,name=proxy_response_start,json=proxyResponseStart,proto3,oneof"`
}

type WebSocketMessage_ProxyResponseChunk struct {
	ProxyResponseChunk *ProxyResponseChunk `protobuf:"bytes,9,opt,name=proxy_response_chunk,json=proxyResponseChunk,proto3,oneof"`
}

type WebSocketMessage_ProxyResponseEnd struct {
	ProxyResponseEnd *ProxyResponseEnd `protobuf:"bytes,10,opt,name=proxy_response_end,json=proxyResponseEnd,proto3,oneof"`
}

func (*WebSocketMessage_RegisterRequest) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_RegisterResponse) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_Heartbeat) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_HeartbeatAck) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_ConfigUpdate) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_EarningsUpdate) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_ProxyRequest) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_ProxyResponseStart) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_ProxyResponseChunk) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_ProxyResponseEnd) isWebSocketMessage_Payload() {}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\x15proxycoin.protocol.v1\x1a\n" +
	"node.proto\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xe7\x01\n" +
	"\fProxyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12:\n" +
	"\x06method\x18\x02 \x01(\x0e2\".proxycoin.protocol.v1.ProxyMethodR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x127\n" +
	"\aheaders\x18\x04 \x03(\v2\x1d.proxycoin.protocol.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x05R\ttimeoutMs\"\xb4\x01\n" +
	"\x12ProxyResponseStart\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x127\n" +
	"\aheaders\x18\x03 \x03(\v2\x1d.proxycoin.protocol.v1.HeaderR\aheaders\x12%\n" +
	"\x0econtent_length\x18\x04 \x01(\x03R\rcontentLength\"h\n" +
	"\x12ProxyResponseChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xb0\x01\n" +
	"\x10ProxyResponseEnd\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x05R\tlatencyMs\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xd9\x06\n" +
	"\x10WebSocketMessage\x12S\n" +
	"\x10register_request\x18\x01 \x01(\v2&.proxycoin.protocol.v1.RegisterRequestH\x00R\x0fregisterRequest\x12V\n" +
	"\x11register_response\x18\x02 \x01(\v2'.proxycoin.protocol.v1.RegisterResponseH\x00R\x10registerResponse\x12@\n" +
	"\theartbeat\x18\x03 \x01(\v2 .proxycoin.protocol.v1.HeartbeatH\x00R\theartbeat\x12J\n" +
	"\rheartbeat_ack\x18\x04 \x01(\v2#.proxycoin.protocol.v1.HeartbeatAckH\x00R\fheartbeatAck\x12J\n" +
	"\rconfig_update\x18\x05 \x01(\v2#.proxycoin.protocol.v1.ConfigUpdateH\x00R\fconfigUpdate\x12P\n" +
	"\x0fearnings_update\x18\x06 \x01(\v2%.proxycoin.protocol.v1.EarningsUpdateH\x00R\x0eearningsUpdate\x12J\n" +
	"\rproxy_request\x18\a \x01(\v2#.proxycoin.protocol.v1.ProxyRequestH\x00R\fproxyRequest\x12]\n" +
	"\x14proxy_response_start\x18\b \x01(\v2).proxycoin.protocol.v1.ProxyResponseStartH\x00R\x12proxyResponseStart\x12]\n" +
	"\x14proxy_response_chunk\x18\t \x01(\v2).proxycoin.protocol.v1.ProxyResponseChunkH\x00R\x12proxyResponseChunk\x12W\n" +
	"\x12proxy_response_end\x18\n" +
	" \x01(\v2'.proxycoin.protocol.v1.ProxyResponseEndH\x00R\x10proxyResponseEndB\t\n" +
	"\apayload*\x82\x01\n" +
	"\vProxyMethod\x12\x1c\n" +
	"\x18PROXY_METHOD_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\b\n" +
	"\x04POST\x10\x02\x12\a\n" +
	"\x03PUT\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04\x12\t\n" +
	"\x05PATCH\x10\x05\x12\b\n" +
	"\x04HEAD\x10\x06\x12\v\n" +
	"\aOPTIONS\x10\a\x12\v\n" +
	"\aCONNECT\x10\bBc\n" +
	"\x1acom.proxycoin.app.protocolB\n" +
	"ProxyProtoZ9github.com/gofullthrottle/proxy-coin/backend/pkg/protocolb\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proxy_proto_goTypes = []any{
	(ProxyMethod)(0),           // 0: proxycoin.protocol.v1.ProxyMethod
	(*Header)(nil),             // 1: proxycoin.protocol.v1.Header
	(*ProxyRequest)(nil),       // 2: proxycoin.protocol.v1.ProxyRequest
	(*ProxyResponseStart)(nil), // 3: proxycoin.protocol.v1.ProxyResponseStart
	(*ProxyResponseChunk)(nil), // 4: proxycoin.protocol.v1.ProxyResponseChunk
	(*ProxyResponseEnd)(nil),   // 5: proxycoin.protocol.v1.ProxyResponseEnd
	(*WebSocketMessage)(nil),   // 6: proxycoin.protocol.v1.WebSocketMessage
	(*RegisterRequest)(nil),    // 7: proxycoin.protocol.v1.RegisterRequest
	(*RegisterResponse)(nil),   // 8: proxycoin.protocol.v1.RegisterResponse
	(*Heartbeat)(nil),          // 9: proxycoin.protocol.v1.Heartbeat
	(*HeartbeatAck)(nil),       // 10: proxycoin.protocol.v1.HeartbeatAck
	(*ConfigUpdate)(nil),       // 11: proxycoin.protocol.v1.ConfigUpdate
	(*EarningsUpdate)(nil),     // 12: proxycoin.protocol.v1.EarningsUpdate
}
var file_proxy_proto_depIdxs = []int32{
	0,  // 0: proxycoin.protocol.v1.ProxyRequest.method:type_name -> proxycoin.protocol.v1.ProxyMethod
	1,  // 1: proxycoin.protocol.v1.ProxyRequest.headers:type_name -> proxycoin.protocol.v1.Header
	1,  // 2: proxycoin.protocol.v1.ProxyResponseStart.headers:type_name -> proxycoin.protocol.v1.Header
	7,  // 3: proxycoin.protocol.v1.WebSocketMessage.register_request:type_name -> proxycoin.protocol.v1.RegisterRequest
	8,  // 4: proxycoin.protocol.v1.WebSocketMessage.register_response:type_name -> proxycoin.protocol.v1.RegisterResponse
	9,  // 5: proxycoin.protocol.v1.WebSocketMessage.heartbeat:type_name -> proxycoin.protocol.v1.Heartbeat
	10, // 6: proxycoin.protocol.v1.WebSocketMessage.heartbeat_ack:type_name -> proxycoin.protocol.v1.HeartbeatAck
	11, // 7: proxycoin.protocol.v1.WebSocketMessage.config_update:type_name -> proxycoin.protocol.v1.ConfigUpdate
	12, // 8: proxycoin.protocol.v1.WebSocketMessage.earnings_update:type_name -> proxycoin.protocol.v1.EarningsUpdate
	2,  // 9: proxycoin.protocol.v1.WebSocketMessage.proxy_request:type_name -> proxycoin.protocol.v1.ProxyRequest
	3,  // 10: proxycoin.protocol.v1.WebSocketMessage.proxy_response_start:type_name -> proxycoin.protocol.v1.ProxyResponseStart
	4,  // 11: proxycoin.protocol.v1.WebSocketMessage.proxy_response_chunk:type_name -> proxycoin.protocol.v1.ProxyResponseChunk
	5,  // 12: proxycoin.protocol.v1.WebSocketMessage.proxy_response_end:type_name -> proxycoin.protocol.v1.ProxyResponseEnd
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	file_node_proto_init()
	file_proxy_proto_msgTypes[5].OneofWrappers = []any{
		(*WebSocketMessage_RegisterRequest)(nil),
		(*WebSocketMessage_RegisterResponse)(nil),
		(*WebSocketMessage_Heartbeat)(nil),
		(*WebSocketMessage_HeartbeatAck)(nil),
		(*WebSocketMessage_ConfigUpdate)(nil),
		(*WebSocketMessage_EarningsUpdate)(nil),
		(*WebSocketMessage_ProxyRequest)(nil),
		(*WebSocketMessage_ProxyResponseStart)(nil),
		(*WebSocketMessage_ProxyResponseChunk)(nil),
		(*WebSocketMessage_ProxyResponseEnd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		EnumInfos:         file_proxy_proto_enumTypes,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
