package com.proxycoin.app.crypto

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import dagger.hilt.android.qualifiers.ApplicationContext
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Wraps the Android Keystore to provide AES-256-GCM encryption/decryption of the
 * wallet private key.
 *
 * The secret key is generated and stored entirely within the hardware-backed
 * Android Keystore — it never leaves the secure enclave. Only the ciphertext
 * (IV prepended) is written to SharedPreferences.
 *
 * Security properties:
 * - AES-256-GCM with a 128-bit authentication tag.
 * - A fresh random IV is generated for every encryption operation.
 * - The IV is stored alongside the ciphertext (first 12 bytes of the Base64 blob).
 * - Key alias: [KEY_ALIAS] — one key per installation.
 */
@Singleton
class KeystoreHelper @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    companion object {
        private const val TAG = "KeystoreHelper"
        private const val KEY_ALIAS = "proxycoin_wallet_key"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_LENGTH = 12
        private const val GCM_TAG_LENGTH = 128 // bits

        private const val PREFS_NAME = "wallet_secure_prefs"
        private const val PREF_ENCRYPTED_KEY = "encrypted_private_key"
    }

    private val keyStore: KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).also { it.load(null) }
    private val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    // ── Public API ────────────────────────────────────────────────────────────

    /**
     * Encrypts [plaintext] using AES-256-GCM and persists the result under [PREF_ENCRYPTED_KEY].
     * Overwrites any previously stored key.
     */
    fun storePrivateKey(plaintext: String) {
        val secretKey = getOrCreateSecretKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        val iv = cipher.iv  // 12 bytes, randomly generated by the Cipher
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))

        // Prefix IV to ciphertext so we can recover it on decryption.
        val combined = ByteArray(iv.size + ciphertext.size)
        System.arraycopy(iv, 0, combined, 0, iv.size)
        System.arraycopy(ciphertext, 0, combined, iv.size, ciphertext.size)

        val encoded = Base64.encodeToString(combined, Base64.NO_WRAP)
        prefs.edit().putString(PREF_ENCRYPTED_KEY, encoded).apply()
        Log.d(TAG, "Private key stored (${ciphertext.size} bytes ciphertext)")
    }

    /**
     * Decrypts and returns the stored private key, or null if none is stored or
     * decryption fails.
     */
    fun retrievePrivateKey(): String? {
        val encoded = prefs.getString(PREF_ENCRYPTED_KEY, null) ?: run {
            Log.d(TAG, "No stored private key found")
            return null
        }

        return try {
            val combined = Base64.decode(encoded, Base64.NO_WRAP)
            if (combined.size <= GCM_IV_LENGTH) {
                Log.e(TAG, "Stored blob too short to contain IV")
                return null
            }

            val iv = combined.copyOfRange(0, GCM_IV_LENGTH)
            val ciphertext = combined.copyOfRange(GCM_IV_LENGTH, combined.size)

            val secretKey = keyStore.getKey(KEY_ALIAS, null) as? SecretKey ?: run {
                Log.e(TAG, "Secret key not found in Keystore")
                return null
            }

            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey, GCMParameterSpec(GCM_TAG_LENGTH, iv))
            val plaintext = cipher.doFinal(ciphertext)
            String(plaintext, Charsets.UTF_8)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to decrypt private key: ${e.message}", e)
            null
        }
    }

    /**
     * Returns true if a private key has been stored (encrypted blob present in prefs).
     * Does not attempt decryption.
     */
    fun hasStoredKey(): Boolean = prefs.contains(PREF_ENCRYPTED_KEY)

    /**
     * Permanently deletes the encrypted key blob and the Keystore entry.
     * This is irreversible — the private key cannot be recovered after calling this.
     */
    fun deleteStoredKey() {
        prefs.edit().remove(PREF_ENCRYPTED_KEY).apply()
        try {
            keyStore.deleteEntry(KEY_ALIAS)
        } catch (e: Exception) {
            Log.w(TAG, "Failed to delete Keystore entry: ${e.message}")
        }
        Log.i(TAG, "Stored key deleted")
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    /**
     * Returns the existing AES-256 secret key from the Keystore, creating it if absent.
     *
     * Key properties:
     * - AES-256 (KeyProperties.KEY_ALGORITHM_AES)
     * - GCM block mode, no padding
     * - Hardware-backed when the device has a secure enclave (StrongBox or TEE)
     * - Not exported; cannot be extracted from the Keystore
     */
    private fun getOrCreateSecretKey(): SecretKey {
        val existing = keyStore.getKey(KEY_ALIAS, null) as? SecretKey
        if (existing != null) return existing

        Log.d(TAG, "Generating new AES-256 key in Keystore")
        val keyGenSpec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setKeySize(256)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setRandomizedEncryptionRequired(true)
            .build()

        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            ANDROID_KEYSTORE,
        )
        keyGenerator.init(keyGenSpec)
        return keyGenerator.generateKey()
    }
}
