// Package metering tracks bandwidth and compute usage per proxy node.
package metering

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/redis/go-redis/v9"
)

const meteringStreamKey = "metering_events"

// Event represents a metering event for a completed proxy request.
type Event struct {
	RequestID  string    `json:"request_id"`
	NodeID     string    `json:"node_id"`
	CustomerID string    `json:"customer_id"`
	BytesIn    int64     `json:"bytes_in"`
	BytesOut   int64     `json:"bytes_out"`
	LatencyMs  int       `json:"latency_ms"`
	StatusCode int       `json:"status_code"`
	Success    bool      `json:"success"`
	Timestamp  time.Time `json:"timestamp"`
}

// eventToValues converts an Event into the field/value map expected by XADD.
func eventToValues(e Event) map[string]any {
	successStr := "false"
	if e.Success {
		successStr = "true"
	}
	return map[string]any{
		"request_id":  e.RequestID,
		"node_id":     e.NodeID,
		"customer_id": e.CustomerID,
		"bytes_in":    strconv.FormatInt(e.BytesIn, 10),
		"bytes_out":   strconv.FormatInt(e.BytesOut, 10),
		"latency_ms":  strconv.Itoa(e.LatencyMs),
		"status_code": strconv.Itoa(e.StatusCode),
		"success":     successStr,
		"timestamp":   e.Timestamp.UTC().Format(time.RFC3339Nano),
	}
}

// eventFromValues reconstructs an Event from a Redis stream entry field map.
func eventFromValues(vals map[string]interface{}) (Event, error) {
	var e Event
	var err error

	e.RequestID, _ = vals["request_id"].(string)
	e.NodeID, _ = vals["node_id"].(string)
	e.CustomerID, _ = vals["customer_id"].(string)

	if v, ok := vals["bytes_in"].(string); ok {
		e.BytesIn, err = strconv.ParseInt(v, 10, 64)
		if err != nil {
			return e, fmt.Errorf("metering: parse bytes_in: %w", err)
		}
	}
	if v, ok := vals["bytes_out"].(string); ok {
		e.BytesOut, err = strconv.ParseInt(v, 10, 64)
		if err != nil {
			return e, fmt.Errorf("metering: parse bytes_out: %w", err)
		}
	}
	if v, ok := vals["latency_ms"].(string); ok {
		e.LatencyMs, err = strconv.Atoi(v)
		if err != nil {
			return e, fmt.Errorf("metering: parse latency_ms: %w", err)
		}
	}
	if v, ok := vals["status_code"].(string); ok {
		e.StatusCode, err = strconv.Atoi(v)
		if err != nil {
			return e, fmt.Errorf("metering: parse status_code: %w", err)
		}
	}
	if v, ok := vals["success"].(string); ok {
		e.Success = v == "true"
	}
	if v, ok := vals["timestamp"].(string); ok {
		e.Timestamp, err = time.Parse(time.RFC3339Nano, v)
		if err != nil {
			return e, fmt.Errorf("metering: parse timestamp: %w", err)
		}
	}
	return e, nil
}

// Reporter publishes metering events to Redis Streams for downstream
// consumption by the reward pipeline and analytics workers.
type Reporter struct {
	client *redis.Client
}

// NewReporter creates a Reporter backed by the given Redis client.
func NewReporter(client *redis.Client) *Reporter {
	return &Reporter{client: client}
}

// Publish appends a single metering event to the Redis stream using XADD.
// The stream ID is auto-generated by Redis (using "*").
func (r *Reporter) Publish(ctx context.Context, event Event) error {
	args := &redis.XAddArgs{
		Stream: meteringStreamKey,
		ID:     "*",
		Values: eventToValues(event),
	}
	if err := r.client.XAdd(ctx, args).Err(); err != nil {
		return fmt.Errorf("metering: publish event %s: %w", event.RequestID, err)
	}
	return nil
}

// PublishBatch appends multiple metering events in a single pipelined XADD
// sequence. It returns the first error encountered, if any.
func (r *Reporter) PublishBatch(ctx context.Context, events []Event) error {
	if len(events) == 0 {
		return nil
	}

	pipe := r.client.Pipeline()
	for _, e := range events {
		pipe.XAdd(ctx, &redis.XAddArgs{
			Stream: meteringStreamKey,
			ID:     "*",
			Values: eventToValues(e),
		})
	}
	_, err := pipe.Exec(ctx)
	if err != nil {
		return fmt.Errorf("metering: batch publish (%d events): %w", len(events), err)
	}
	return nil
}

// CreateConsumerGroup creates a consumer group for the metering stream.
// It uses the special "$" start ID so consumers only see new messages.
// Returns nil if the group already exists.
func (r *Reporter) CreateConsumerGroup(ctx context.Context, group string) error {
	err := r.client.XGroupCreateMkStream(ctx, meteringStreamKey, group, "$").Err()
	if err != nil && err.Error() != "BUSYGROUP Consumer Group name already exists" {
		return fmt.Errorf("metering: create consumer group %q: %w", group, err)
	}
	return nil
}

// ReadEvents reads up to count undelivered messages from the stream for the
// given consumer group and consumer name using XREADGROUP.
func (r *Reporter) ReadEvents(ctx context.Context, group, consumer string, count int64) ([]Event, error) {
	msgs, err := r.client.XReadGroup(ctx, &redis.XReadGroupArgs{
		Group:    group,
		Consumer: consumer,
		Streams:  []string{meteringStreamKey, ">"},
		Count:    count,
		Block:    0,
	}).Result()
	if err != nil {
		return nil, fmt.Errorf("metering: read events (group=%s consumer=%s): %w", group, consumer, err)
	}

	var events []Event
	for _, stream := range msgs {
		for _, msg := range stream.Messages {
			e, err := eventFromValues(msg.Values)
			if err != nil {
				return nil, err
			}
			events = append(events, e)
		}
	}
	return events, nil
}

// AckEvent acknowledges one or more message IDs for the consumer group using
// XACK, signalling that they have been processed successfully.
func (r *Reporter) AckEvent(ctx context.Context, group string, ids ...string) error {
	if err := r.client.XAck(ctx, meteringStreamKey, group, ids...).Err(); err != nil {
		return fmt.Errorf("metering: ack events (group=%s ids=%v): %w", group, ids, err)
	}
	return nil
}

// StreamLength returns the current number of entries in the metering stream
// via XLEN.
func (r *Reporter) StreamLength(ctx context.Context) (int64, error) {
	n, err := r.client.XLen(ctx, meteringStreamKey).Result()
	if err != nil {
		return 0, fmt.Errorf("metering: stream length: %w", err)
	}
	return n, nil
}

// TrimStream removes entries from the metering stream so that at most maxLen
// entries remain, using an approximate XTRIM with MAXLEN.
func (r *Reporter) TrimStream(ctx context.Context, maxLen int64) error {
	if err := r.client.XTrimMaxLen(ctx, meteringStreamKey, maxLen).Err(); err != nil {
		return fmt.Errorf("metering: trim stream to %d: %w", maxLen, err)
	}
	return nil
}
